### ISSUE TITLE
Support chapters

### ISSUE THREAD

**Issue by doughsay** [doughsay/ambry#21]
This is a bit of an open-ended or "hard" problem to solve, since there's no guarantee any chapter information will be present in any uploaded source files.

* sometimes audiobooks are split into mp3 files by chapter
* sometimes m4b files contain embedded chapter metadata
* sometimes no chapter information is present

So the problem is two fold:

1. If chapter information is present in some way and we can reliably know that it _is_ present, then we need to implement a data-model to store the information
2. Once we do have chapter information, we need to build a UI to view/select chapters, and to change the "next"/"previous" buttons to allow skipping to chapter boundaries

Additionally, it would then also be nice to improve the sleep-timer feature to allow for "play until end of chapter".

**Comment by kerbymart** [comment]
Hi @doughsay 

How does Ambry handle audiobooks that lack metadata, including basic information and covers?

Does Ambry fetch metadata and covers from platforms like Audible when handling audiobooks that lack such information?

**Comment by doughsay** [comment]
@kerbymart at the moment, most metadata stuff is pretty manual, nothing is automatic, but you can import descriptions, images and chapters from the Audnexus API (backed by the Audible API), which makes things a little bit easier.  Ambry is a little different than other kinds of media streaming platforms because it doesn't auto-import media files, it requires you to manually create the books/authors/narrators, and upload the files for the audiobooks.  I hope in the future I can make the process a bit more streamlined and automatic, but right now it's not.

**Comment by kerbymart** [comment]
I've been pondering over the state of my expansive audiobook library, which spans over a thousand non-fiction titles. The current management process is rather unwieldy, and I've been brainstorming some ideas on how to improve it. I thought I'd share some thoughts:

## Audio Formats

My library is a mix of MP3 and M4B files, although I've started converting them to OPUS. This codec reduces the file size by about 80% without sacrificing audio quality. That being said, it's essential for any audiobook manager to support a variety of audio formats, including newer codecs like Opus and perhaps even Google's Lyra.

## File Upload

The audiobook manager should be versatile enough to handle different types of audiobook packages - from single files to folders, and even compressed files like ZIP or RAR. It should be able to intelligently process these files and, if possible, merge multi-file audios into a single track or at least create markers for a seamless user experience. Currently, my process involves using `ffmpeg` to batch merge audiobooks via scripting.

## Chapter Separation

One of the major challenges with audiobooks is handling chapters, especially when the metadata is missing. Many players treat audiobooks without metadata like music, which isn't ideal. One potential solution to this could be using Machine Learning models like OpenAI's Whisper. 

Typically, audiobooks have a distinct pattern when transitioning from one chapter to the next - a pause, followed by the word 'CHAPTER', and another pause. This pattern could be used as a starting point for marking chapters. It's a sort of brute-force method for audiobooks lacking metadata, but it may be our best bet given the absence of an Audiobook API that could provide this information. (In which I doubt that such API would ever happen 😅)

## Metadata

As for other metadata like titles, authors, summaries, etc., I've heard about Audnexus, but I'm not certain if it's still maintained. My background in web technologies has led me to consider an alternative approach - web scraping. 

The idea is to use a headless browser to access sites like Audible or Google Books and extract the necessary information.  This approach leverages the fact that these platforms display book information even when not logged in, which makes them viable sources for metadata.. This process should be performed on the local machine to avoid being blocked by the web servers of these audiobook platforms.

## Conclusion

In my opinion, popular self-hosted audiobook apps fall short in providing a listening experience comparable to that offered by services like Audible or Spotify. This is primarily due to the cumbersome management of audiobooks. I believe the strategies I've outlined could help mitigate these issues and enhance the user experience.

**Comment by kerbymart** [comment]
@doughsay you mentioened:

> Ambry is a little different than other kinds of media streaming platforms because it doesn't auto-import media files, it requires you to manually create the books/authors/narrators, and upload the files for the audiobooks. 

You're right, I had the same idea, Audiobook managers should not be file-oriented, but book/audiobook-oriented. It's about the titles after all.

**Comment by doughsay** [comment]
Hey @kerbymart, thanks for all the detailed thoughts on this. I think your ideas and the goals of Ambry mostly align well; I'd love it if you could give it a try and see if you like what it does now and if you think it could grow into something a lot more usable for your use-case. I'm still very actively working on it and am open to doing some rather major overhauls of things to make it more useful.  It's pretty useful for my use-case right now, but it definitely could be better.  In any case, we should move this conversation out of this old closed issue into a more suitable place.

GitHub discussions should be the right place to do this, so I've started a thread here: https://github.com/ambry-app/ambry/discussions/571  If you want to continue, can you copy your thoughts into that thread?  Thanks!
